# Generated by Django 4.2.7 on 2023-12-01 23:29

import api.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(upload_to=api.catalog.models.upload_banner, verbose_name='Banner'),
        ),
    ]
