# Generated by Django 4.2.7 on 2024-01-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_favourite_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesproduct',
            old_name='image',
            new_name='path',
        ),
    ]
